"use client";

import { motion } from "framer-motion";
import Image from "next/image";
import { ExternalLink, ArrowRight } from "lucide-react";
import { Reveal, StaggerReveal, staggerItem } from "@/components/motion/reveal";
import { SpotlightCard } from "@/components/motion/spotlight-card";
import { TiltCard } from "@/components/motion/tilt-card";
import { cn } from "@/lib/utils";

const VENTURES = [
  {
    id: "rune",
    title: "Rune",
    desc: "🚀 Rune is your all-in-one productivity toolkit featuring 145+ powerful tools for learning, creating, and working smarter. From text & writing tools, PDF management, image editing, video processing, to developer utilities, calculators, and AI-powered assistants—Rune empowers students, professionals, and creators with free 24/7 access to streamline their workflow.",
    image: "/images/rune.png",
    link: "https://rune.codes",
    stack: ["React_dark.svg", "typescript.svg", "nextjs_icon_dark.svg", "tailwindcss.svg", "RuneLogo.svg", "Motion_dark.svg", "nodejs.svg", "Vercel_dark.svg"],
    features: [
      "145+ free tools including text editors, PDF converters, and image processors",
      "AI-powered tools for writing, summarizing, and content creation",
      "Developer utilities with JSON formatter, regex tester, and code tools"
    ]
  },
  {
    id: "runehub",
    title: "RuneHub",
    desc: "🚀 RuneHub is a comprehensive programming education platform featuring extensive tutorials and articles on different programming languages, frameworks, and technologies. It includes a dedicated tech trends section with the latest industry news and insights, now powered by its own powerful custom CMS.",
    image: "/images/runehub.png",
    link: "https://rune.codes/hub",
    stack: ["React_dark.svg", "typescript.svg", "nextjs_icon_dark.svg", "tailwindcss.svg", "RuneLogo.svg", "Motion_dark.svg"],
    features: [
      "62+ topics to study across different programming languages and technologies",
      "RuneAI powered key insights for accelerated learning",
      "Developer focused UX with its own powerful custom CMS"
    ]
  },
  {
    id: "runelearn",
    title: "RuneLearn",
    desc: "🚀 RuneLearn is an ultimate AI-powered study companion that dynamically generates quizzes, intelligent flashcards, personalized roadmaps, and instantly resolves doubts with its deep-context advanced doubt solver.",
    image: "/images/runelearn.png",
    link: "https://rune.codes/learn",
    stack: ["React_dark.svg", "typescript.svg", "nextjs_icon_dark.svg", "tailwindcss.svg", "RuneLogo.svg", "Vercel_dark.svg"],
    features: [
      "Interactive Quizzes and Flashcards dynamically generated by AI",
      "Personalized Learning Roadmaps tailored to your study goals",
      "Advanced Doubt Solver providing in-depth explanations instantly"
    ]
  },
  {
    id: "runeai",
    title: "RuneAI",
    desc: "🚀 Rune AI featuring a powerful RAG system, three specialized models (Fast, Thinking, Pro), and a massive 500K context limit. Includes advanced Web Search capable of deep research and intelligent Tool Calling automation.",
    image: "/images/1runeai.png",
    link: "https://ai.rune.codes",
    stack: ["RuneLogo.svg", "langgraph.svg", "tavily.svg", "appwrite.svg", "nextjs_icon_dark.svg", "Vercel_dark.svg"],
    features: [
      "Powered by its own dedicated server for AI models hosted on Digital Ocean",
      "Massive 500K context limit for deep document analysis",
      "Advanced Web Search and intelligent automated Tool Calling"
    ]
  }
];

export function VentureShowcase(): React.JSX.Element {
  return (
    <section id="work" className="relative py-24 md:py-32 bg-black">
      <div className="mx-auto max-w-7xl px-6">
        <StaggerReveal className="flex flex-col gap-32">
          {VENTURES.map((v, i) => (
            <motion.div key={v.id} variants={staggerItem} className={cn("flex flex-col gap-12", i % 2 === 1 ? "md:flex-row-reverse" : "md:flex-row")}>
              {/* Content Side */}
              <div className="flex flex-1 flex-col gap-8">
                <div className="flex flex-col gap-4">
                  <Reveal delay={0.1} direction={i % 2 === 1 ? "left" : "right"}>
                    <h3 className="text-4xl md:text-6xl font-black text-white">{v.title}</h3>
                  </Reveal>
                  <Reveal delay={0.2}>
                    <p className="text-lg text-white/60 leading-relaxed max-w-xl">{v.desc}</p>
                  </Reveal>
                </div>

                <ul className="flex flex-col gap-3">
                  {v.features.map((f, fi) => (
                    <Reveal key={fi} delay={0.3 + fi * 0.1} direction="none">
                      <li className="flex items-start gap-3 text-sm text-white/80">
                        <div className="mt-1.5 h-1.5 w-1.5 rounded-full bg-accent shrink-0" />
                        {f}
                      </li>
                    </Reveal>
                  ))}
                </ul>

                <div className="flex flex-wrap gap-4">
                  {v.stack.map((icon, si) => (
                    <Reveal key={si} delay={0.5 + si * 0.05} direction="down">
                      <div className="relative h-8 w-8 grayscale hover:grayscale-0 transition-all">
                        <Image src={`/icons/${icon}`} alt="" fill className="object-contain" />
                      </div>
                    </Reveal>
                  ))}
                </div>

                <Reveal delay={0.7}>
                  <a href={v.link} target="_blank" rel="noopener noreferrer" 
                    className="inline-flex items-center gap-2 text-white font-bold hover:text-accent transition-colors group">
                    Visit Project <ArrowRight size={18} className="group-hover:translate-x-1 transition-transform" />
                  </a>
                </Reveal>
              </div>

              {/* Visual Side */}
              <div className="flex-1">
                <TiltCard maxTilt={5}>
                  <SpotlightCard className="p-0 border-white/10 bg-white/5 overflow-hidden aspect-[4/3]">
                    <div className="relative h-full w-full p-4 md:p-8">
                      <div className="absolute inset-0 bg-gradient-to-br from-accent/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                      <div className="relative h-full w-full rounded-lg overflow-hidden border border-white/10 shadow-2xl">
                        <Image src={v.image} alt={v.title} fill className="object-cover" />
                      </div>
                    </div>
                  </SpotlightCard>
                </TiltCard>
              </div>
            </motion.div>
          ))}
        </StaggerReveal>
        
        <Reveal className="mt-32 flex justify-center">
          <a href="https://github.com/ksparth12" target="_blank" rel="noopener noreferrer"
            className="px-8 py-4 rounded-full border border-white/10 bg-white/5 text-white font-bold hover:bg-white/10 transition-all flex items-center gap-3">
            See more projects <ExternalLink size={18} />
          </a>
        </Reveal>
      </div>
    </section>
  );
}
